README.md

Attempting to run what's given in the readme file currently results in a RuntimeError:
```
$ zold --trace --verbose --invoice=ceda7c5ff887de31 --host=46.101.148.53
ERROR: A command required, try --help (RuntimeError)
/var/lib/gems/2.3.0/gems/zold-0.10.21/bin/zold:112:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

#168 Fix incorrect commands to run zold node

---

lib/zold/atomic_file.rb
test/test_atomic_file.rb

https://github.com/zold-io/zold/issues/264 `AtomicFile#write` should be thread safe and not corrupt data that ends up in the file. `#synchronize` is the way to do it.

AtomicFile#write corrupts data when multiple threads call it

---

lib/zold/commands/pay.rb
test/commands/test_pay.rb

I would have liked to test all info output, but the wallet ids are different every time.

Fix #79: notify about taxes after each PAY

---

lib/zold/tax.rb

Sorry for the additional PR referencing issue #305, I had to remove an unused reference to the digest library that was unused.

#305 - Removed reference to unused digest library

---

Rakefile
test/test__helper.rb

Now it is possible to suppress verbose logs for `rake` / `rake test`, using the `-- quiet` option. 
E.g. `rake --quiet`
refers to: #307

Add --quiet option to rake test

---

test/test_upgrades.rb

https://github.com/zold-io/zold/issues/327
I'm having real upgrade scripts run and output `upgrading to <version>`, which I'm checking in tests.

Fix #327: add upgrade manager tests

---

upgrades/0.0.0.rb

#358 
**Status:** _This PR is here as a supporting evidence for #372, it's not finished yet._
_At the moment the naming is wrong, it should be `upgrades/2.rb`, but until #369 is implemented, we cannot use the name, because the validation validates `x.y.z` format of version. Once this is done, `PROTOCOL` needs to be bumped._

Upgrade script to rename wallet -> wallet.z #358

---

lib/zold/node/farm.rb
lib/zold/score.rb
test/node/test_farm.rb

Issue #297 When a line of the farm file contains garbage, now it gets ignored and a message is written to the log.

Issue #297 implemented: when file contains garbage the line is ignored

---

bin/zold
lib/zold/commands/alias.rb
test/commands/test_alias.rb

#322
**Few side notes:**
- It was explained to me that the process is to start with a skipped tests and a pdd comment. Here, since the command file has been added first and it raises `NotImplementedError`, I don’t skip the test, but I (have to) check whether `NotImplementedError` is raised. Side-advantage of that is once the command is implemented, the tests will fail, prompting whoever is working on it to update them.
- The aforementioned PDD comment is already there (in the command file), hence I’m not introducing a new one.

Add tests for the alias command #322

---

lib/zold/txn.rb

As asked in issue #341 I have been removing all occurrences of regexp when a numeric index was specified instead of using named matches

Issue #341 - Fixing regexp in Txn class

---

test/commands/test_pull.rb
test/fake_home.rb

As requested in issue #324, I have created a test for pull command showing hot to mock a pull request of a wallet.
Basically this is what I am doing:
- Add a mock remote;
- Generating a fake response for a wallet, by creating a proper wallet (in a separate directory);
- stubbing the response of _/wallet_ call;
- execute the _Pull_ command;
- testing if the wallet has been correctly merged;

Issue #324 - Adding new test for pull showing how to mock a pull wallet

---

appveyor.yml

For appveyor in issue #231  to successfully build openssl, we have to download precompiled headers for Windows and use them for bundle

Issue #231 - Downloading openssl headers for appveyor

---

lib/zold/commands/node.rb
lib/zold/node/front.rb
test/node/test_front.rb

For issue #249 I added a new _alias_ parameter to _node_ command to assign an alphanumeric string to a node. This string is then included in the mail REST responses.
Please note that _alias_ is a reserved word, so I hade to call the internal attribute _node_alias_ to avoid conflicts

Issue 249 - Node alias

---

lib/zold/commands/node.rb

PR for #134 
remove node itself from remote while node onboarding using `remote` command. `--force` argument prevents to fail if current node is not in `remotes` list.

#134 - remove node itself from remote while node onboarding

---

fixtures/scripts/redeploy-on-upgrade.sh

Trying to fix the problem reported in issue #553 I run many times `rake` but just a few times the test on subject failed, so it is really difficult to find the reason why of the failing.
Also, the output in the failing case doesn't differs that much from the good one.
By analyzing the code however, I noticed that only on that particular test it was added the `--memory-dump` option, that is used to check memory consumption by the library. 
It is not required in this test to check the memory usage, and also it is specified in `memory profiler gem` that by using it it could slow down the application, and this could be a reason why sometimes the test fails.
Therefore, I just removed that option, let's see if the problem arises again in the future.

Issue #553 - Redeploy on upgrade fix

---

lib/zold/dir_items.rb
test/test_dir_items.rb

#511
It seems that **Shellwords::escape** output is incompatible with **POSIX::Spawn::Child**. Sending the shell command arguments works fine without escaping them with **Shellwords::escape**.

Remove unnecessary escaping for shell commands in DirItems

---

.rultor.yml

Issue #556 
To solve this, after building the gem I added a step where:
- installs rvm and the last stable version of ruby;
- installs the local version of zold that has just being built;
- run `zold remote update`;
If the last command fails, the whole procedure will be interrupted.

Issue #556 - Rultor integration test

---

lib/zold/cached_wallets.rb
lib/zold/node/front.rb
lib/zold/sync_wallets.rb
lib/zold/tree_wallets.rb
lib/zold/wallets.rb
test/test_tree_wallets.rb
test/test_wallets.rb

#514 
I added **count** method to _Wallets_ and _TreeWallets_.  _Wallets#count_ performs a tradditional count of any file in its directory while _TreeWallets#count_ traverse through a directory hierarchy and performs a count.

#514 improve total_wallets count

---

test/test_http.rb

Issue #560 
I modified the test by breaking the loop when a "\r\n" is returned

Issue #560 - Fixed problem with test

---

lib/zold/node/front.rb
test/node/test_front.rb

Issue #618
I added a new test and code for new endpoint `/wallets`, returning a list of all wallets' id known to the node, separated by `\n`

Issue #618 - New endpoint /wallets

---

Dockerfile
README.md
node.sh

You could create a docker hub image which will be automatically build from dockerfile in this repository. something like zold-io/zold:latest so users could run the node as 
```
docker run -d -p 4096:4096 zold-io/zold:latest /node.sh --host=<your host IP> --invoice=17737fee5b825835
```
Tested on linux and mac only. Should work on Windows too.

Simple docker container to run zold node
